services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: unless-stopped
    env_file: .env.staging
    volumes:
      - ./data-staging:/data
    ports:
      - "8081:8080"

  ssh:
    build:
      context: .
      dockerfile: Dockerfile.ssh
    restart: unless-stopped
    env_file: .env.staging
    ports:
      - "2222:22"
    volumes:
      - ./.ssh:/root/.ssh
    depends_on:
      - api
